export interface GalleryImage {
  id: string;
  src: string;
  alt: string;
  category: string;
  venue: "Indoor" | "Outdoor" | "Both";
  colorTheme: string;
  budget: "Budget" | "Mid-Range" | "Premium";
  location: string;
  description: string;
}

export const galleryImages: GalleryImage[] = [
  {
    id: "1",
    src: "https://images.unsplash.com/photo-1519741497674-611481863552?w=800",
    alt: "Elegant wedding stage decoration with white and gold balloons",
    category: "Wedding",
    venue: "Indoor",
    colorTheme: "White & Gold",
    budget: "Premium",
    location: "Delhi",
    description:
      "Luxurious wedding stage setup with cascading balloon garlands",
  },
  {
    id: "2",
    src: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800",
    alt: "Colorful birthday party decoration",
    category: "Birthday",
    venue: "Indoor",
    colorTheme: "Rainbow",
    budget: "Mid-Range",
    location: "Gurgaon",
    description: "Vibrant rainbow themed birthday celebration for kids",
  },
  {
    id: "3",
    src: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800",
    alt: "Corporate event stage setup",
    category: "Corporate",
    venue: "Indoor",
    colorTheme: "Blue & White",
    budget: "Premium",
    location: "Noida",
    description: "Professional corporate annual day celebration setup",
  },
  {
    id: "4",
    src: "https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?w=800",
    alt: "Romantic ring ceremony decoration",
    category: "Ring Ceremony",
    venue: "Indoor",
    colorTheme: "Pink & Gold",
    budget: "Mid-Range",
    location: "Delhi",
    description: "Elegant engagement backdrop with floral accents",
  },
  {
    id: "5",
    src: "https://images.unsplash.com/photo-1464349153735-7db50ed83c84?w=800",
    alt: "Kids birthday party with balloon arch",
    category: "Birthday",
    venue: "Indoor",
    colorTheme: "Pastel",
    budget: "Budget",
    location: "Faridabad",
    description: "Adorable pastel themed birthday for little ones",
  },
  {
    id: "6",
    src: "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=800",
    alt: "Outdoor wedding mandap decoration",
    category: "Wedding",
    venue: "Outdoor",
    colorTheme: "Red & Gold",
    budget: "Premium",
    location: "Gurgaon",
    description: "Traditional mandap with modern balloon elements",
  },
  {
    id: "7",
    src: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800",
    alt: "Baby shower decoration with balloons",
    category: "Baby Shower",
    venue: "Indoor",
    colorTheme: "Blue & White",
    budget: "Mid-Range",
    location: "Delhi",
    description: "Its a Boy themed baby shower celebration",
  },
  {
    id: "8",
    src: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800",
    alt: "Corporate conference decoration",
    category: "Corporate",
    venue: "Indoor",
    colorTheme: "Brand Colors",
    budget: "Premium",
    location: "Gurgaon",
    description: "Tech conference stage with branded decorations",
  },
  {
    id: "9",
    src: "https://images.unsplash.com/photo-1529543544277-750e8293e5ce?w=800",
    alt: "Anniversary surprise room decoration",
    category: "Anniversary",
    venue: "Indoor",
    colorTheme: "Red & Pink",
    budget: "Budget",
    location: "Delhi",
    description: "Romantic room surprise for wedding anniversary",
  },
  {
    id: "10",
    src: "https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800",
    alt: "Themed birthday party setup",
    category: "Birthday",
    venue: "Indoor",
    colorTheme: "Theme Based",
    budget: "Premium",
    location: "Noida",
    description: "Superhero themed party with custom decorations",
  },
  {
    id: "11",
    src: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800",
    alt: "Wedding entrance gate decoration",
    category: "Wedding",
    venue: "Both",
    colorTheme: "White & Pink",
    budget: "Premium",
    location: "Delhi",
    description: "Grand wedding entrance with balloon columns",
  },
  {
    id: "12",
    src: "https://images.unsplash.com/photo-1519689680058-324335c77eba?w=800",
    alt: "Baby shower cake table setup",
    category: "Baby Shower",
    venue: "Indoor",
    colorTheme: "Pink & White",
    budget: "Mid-Range",
    location: "Ghaziabad",
    description: "Its a Girl themed dessert table decoration",
  },
  {
    id: "13",
    src: "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=800",
    alt: "Engagement photo booth",
    category: "Ring Ceremony",
    venue: "Indoor",
    colorTheme: "Rose Gold",
    budget: "Premium",
    location: "Gurgaon",
    description: "Elegant photo booth setup for ring ceremony",
  },
  {
    id: "14",
    src: "https://images.unsplash.com/photo-1496843916299-590492c751f4?w=800",
    alt: "Birthday balloon bouquet",
    category: "Birthday",
    venue: "Indoor",
    colorTheme: "Gold & Black",
    budget: "Budget",
    location: "Delhi",
    description: "Stylish balloon bouquets for milestone birthday",
  },
  {
    id: "15",
    src: "https://images.unsplash.com/photo-1478146896981-b80fe463b330?w=800",
    alt: "Wedding reception decoration",
    category: "Wedding",
    venue: "Indoor",
    colorTheme: "Purple & Silver",
    budget: "Premium",
    location: "Noida",
    description: "Stunning reception hall transformation",
  },
  {
    id: "16",
    src: "https://images.unsplash.com/photo-1522344008469-e25f8d33b4a1?w=800",
    alt: "Anniversary dinner setup",
    category: "Anniversary",
    venue: "Indoor",
    colorTheme: "Romantic Red",
    budget: "Mid-Range",
    location: "Delhi",
    description: "Intimate anniversary dinner decoration",
  },
  {
    id: "17",
    src: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800",
    alt: "Corporate team building event",
    category: "Corporate",
    venue: "Outdoor",
    colorTheme: "Colorful",
    budget: "Mid-Range",
    location: "Faridabad",
    description: "Fun corporate team event decoration",
  },
  {
    id: "18",
    src: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
    alt: "Gender reveal decoration",
    category: "Baby Shower",
    venue: "Indoor",
    colorTheme: "Pink & Blue",
    budget: "Premium",
    location: "Gurgaon",
    description: "Exciting gender reveal party setup",
  },
  {
    id: "19",
    src: "https://images.unsplash.com/photo-1529636798458-92182e662485?w=800",
    alt: "Engagement party decoration",
    category: "Ring Ceremony",
    venue: "Both",
    colorTheme: "White & Gold",
    budget: "Mid-Range",
    location: "Delhi",
    description: "Sophisticated engagement celebration decor",
  },
  {
    id: "20",
    src: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800",
    alt: "Grand celebration setup",
    category: "Event Management",
    venue: "Indoor",
    colorTheme: "Multi-color",
    budget: "Premium",
    location: "Gurgaon",
    description: "Complete event transformation with premium decor",
  },
];

export const galleryCategories = [
  "All",
  "Wedding",
  "Birthday",
  "Corporate",
  "Ring Ceremony",
  "Baby Shower",
  "Anniversary",
  "Event Management",
];

export const venueTypes = ["All", "Indoor", "Outdoor"];

export const budgetRanges = ["All", "Budget", "Mid-Range", "Premium"];
